/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LobbyLazyImport = createFileRoute('/Lobby')()
const GameLazyImport = createFileRoute('/Game')()
const AppLazyImport = createFileRoute('/App')()

// Create/Update Routes

const LobbyLazyRoute = LobbyLazyImport.update({
  path: '/Lobby',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Lobby.lazy').then((d) => d.Route))

const GameLazyRoute = GameLazyImport.update({
  path: '/Game',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Game.lazy').then((d) => d.Route))

const AppLazyRoute = AppLazyImport.update({
  path: '/App',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/App.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppLazyImport
      parentRoute: typeof rootRoute
    }
    '/Game': {
      id: '/Game'
      path: '/Game'
      fullPath: '/Game'
      preLoaderRoute: typeof GameLazyImport
      parentRoute: typeof rootRoute
    }
    '/Lobby': {
      id: '/Lobby'
      path: '/Lobby'
      fullPath: '/Lobby'
      preLoaderRoute: typeof LobbyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AppLazyRoute,
  GameLazyRoute,
  LobbyLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/App",
        "/Game",
        "/Lobby"
      ]
    },
    "/App": {
      "filePath": "App.lazy.tsx"
    },
    "/Game": {
      "filePath": "Game.lazy.tsx"
    },
    "/Lobby": {
      "filePath": "Lobby.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
